language: java
jdk:
  - oraclejdk7
branches:
  only:
    - master
before_deploy:
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${NAME}
  - git tag ${VERSION_PREFIX}${TRAVIS_BUILD_NUMBER}
  - git push -q ${REPO} --tags
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "/home/travis/.m2/repository/yushijinhun/advancedcommands/AdvancedCommands/${VERSION_PREFIX}${TRAVIS_BUILD_NUMBER}/AdvancedCommands-${VERSION_PREFIX}${TRAVIS_BUILD_NUMBER}.jar"
  skip_cleanup: true
  on:
    tags: false

