language: java
jdk:
  - oraclejdk7
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "/home/travis/.m2/repository/yushijinhun/advancedcommands/AdvancedCommands/${VERSION_PREFIX}${TRAVIS_BUILD_NUMBER}/AdvancedCommands-${VERSION_PREFIX}${TRAVIS_BUILD_NUMBER}.jar"
  skip_cleanup: true
  on:
    tags: false

