name: "AdvancedCommands"
main: "yushijinhun.advancedcommands"
version: "0.2"
commands:
   exp:
      description: "Execute a expression"
      usage: "/exp <experssion>"
      permission: "advancedcommands.exp"
      permission-message: "You don't have permission"
permissions:
    advancedcommands.*:
        description: "Gives access to all AdvancedCommands commands"
        children:
            advancedcommands.exp: true
    advancedcommands.exp:
        description: "Allows you to execute a expression"
        default: op
