name: "AdvancedCommands"
main: "yushijinhun.advancedcommands.AdvancedCommands"
version: "${VERSION}"
depend: ["ProtocolLib"]
commands:
   exp:
      description: "Execute a expression"
      usage: "/exp <experssion>"
      permission: "advancedcommands.exp"
      permission-message: "You don't have permission"
   varTable:
      description: "Save/Load the var table"
      usage: "/varTable <save|load|load!>"
      permission: "advancedcommands.varTable"
      permission-message: "You don't have permission"
permissions:
    advancedcommands.*:
        description: "Gives access to all AdvancedCommands commands"
        children:
            advancedcommands.exp: true
            advancedcommands.varTable: true
    advancedcommands.exp:
        description: "Allows you to execute a expression"
        default: op
    advancedcommands.varTable:
        description: "Allows you to save/load the var table"
        default: op

